# Generated by Django 4.1.3 on 2022-12-09 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingsTEM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorszam', models.IntegerField()),
                ('szerkezeti_hossz', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='BuildingsTKB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorszam', models.IntegerField()),
                ('szerkezeti_hossz', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='BuildingsTMO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorszam', models.IntegerField()),
                ('szerkezeti_hossz', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='BuildingsTU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorszam', models.IntegerField()),
                ('szerkezeti_hossz', models.FloatField()),
            ],
        ),
    ]
