# Generated by Django 4.1.3 on 2023-02-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingsTEM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorszam', models.IntegerField()),
                ('szerkezeti_hossz', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='BuildingsTKB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorszam', models.IntegerField()),
                ('szerkezeti_hossz', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='BuildingsTMO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorszam', models.IntegerField()),
                ('szerkezeti_hossz', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='BuildingsTU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorszam', models.IntegerField()),
                ('szerkezeti_hossz', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('position_HU', models.CharField(max_length=50)),
                ('position_EN', models.CharField(max_length=50)),
                ('address_1', models.CharField(max_length=50)),
                ('address_2', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='JelkodCCS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notation', models.CharField(max_length=5)),
                ('length', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='JelkodVVS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notation', models.CharField(max_length=5)),
                ('length', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=100)),
                ('position_HU', models.CharField(max_length=50)),
                ('position_EN', models.CharField(max_length=50)),
                ('signature', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
