# Generated by Django 4.1.3 on 2023-03-15 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmw', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BuildingsTEM',
            new_name='BuildingsGEM',
        ),
        migrations.RenameModel(
            old_name='BuildingsTMO',
            new_name='BuildingsGKB',
        ),
        migrations.RenameModel(
            old_name='BuildingsTU',
            new_name='BuildingsGMO',
        ),
        migrations.RenameModel(
            old_name='BuildingsTKB',
            new_name='BuildingsGU',
        ),
    ]
