# Generated by Django 4.1.3 on 2023-01-13 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmw', '0002_jelkkodccs_jelkodvvs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JelkkodCCS',
            new_name='JelkodCCS',
        ),
    ]
