# Generated by Django 4.1.3 on 2023-02-09 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact', models.CharField(max_length=50, null=True, verbose_name='Műtárgy')),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('state', models.CharField(choices=[('untouched', 'untouched'), ('draft', 'draft'), ('done', 'done')], default='untouched', max_length=15)),
                ('employees_on_leave', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20, verbose_name='Rendszám')),
                ('vehicle_name', models.CharField(max_length=30, verbose_name='Autó neve')),
            ],
        ),
        migrations.CreateModel(
            name='Subproject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subproject', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('customer', models.CharField(max_length=100, null=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subproject', to='schedule.project')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(max_length=50, null=True, verbose_name='Szelvény')),
                ('length', models.IntegerField(null=True)),
                ('measurement_side', models.CharField(max_length=10, null=True)),
                ('longitude', models.FloatField(null=True)),
                ('latitude', models.FloatField(null=True)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.artifact')),
            ],
        ),
        migrations.CreateModel(
            name='DateBoundWithProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('artifact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.artifact')),
                ('date', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.date')),
                ('employee', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('profile', models.ManyToManyField(blank=True, to='schedule.profile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='schedule.project')),
                ('subproject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.subproject')),
                ('vehicle', models.ManyToManyField(to='schedule.vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='artifact',
            name='subproject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.subproject'),
        ),
    ]
