# Generated by Django 4.1.3 on 2022-12-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('empty', models.BooleanField()),
                ('half_ready', models.BooleanField()),
                ('ready', models.BooleanField()),
            ],
        ),
    ]
