# Generated by Django 4.1.3 on 2022-12-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_employee_vehicle_project_dates_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dates',
            name='project',
        ),
        migrations.AddField(
            model_name='dates',
            name='project',
            field=models.ManyToManyField(null=True, to='schedule.project'),
        ),
    ]
