# Generated by Django 4.1.3 on 2023-02-09 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
