# Generated by Django 4.1.3 on 2022-12-05 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_remove_project_employee_remove_project_vehicle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dates',
            name='project',
        ),
        migrations.AddField(
            model_name='dates',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.project'),
        ),
    ]
