# Generated by Django 4.1.3 on 2023-02-10 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
