# Generated by Django 4.1.3 on 2023-02-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test45',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdkgju', models.CharField(max_length=5)),
            ],
        ),
    ]
