# Generated by Django 4.1.3 on 2022-12-05 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_remove_dates_project_dates_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='project',
            name='vehicle',
        ),
        migrations.DeleteModel(
            name='Dates',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
