# Generated by Django 4.1.3 on 2022-12-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_remove_project_employee_remove_project_vehicle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(choices=[('Karácsonyi CS', 2), ('Fadíszítés', 1)], max_length=50)),
            ],
        ),
    ]
