# Generated by Django 4.1.3 on 2023-02-10 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_test45'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test45',
        ),
    ]
