# Generated by Django 4.1.3 on 2022-12-05 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_date_alter_project_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='projects',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='schedule.project'),
        ),
    ]
