# Generated by Django 4.1.3 on 2023-03-15 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_sit_project_sit_with_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artifact',
            options={'verbose_name': 'Műtárgy', 'verbose_name_plural': 'Műtárgyak'},
        ),
        migrations.AlterModelOptions(
            name='date',
            options={'verbose_name': 'Dátum', 'verbose_name_plural': 'Dátumok'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Süllyedésmérő cső', 'verbose_name_plural': 'Süllyedésmérő csövek'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Munkatípus', 'verbose_name_plural': 'Munkatípusok'},
        ),
        migrations.AlterModelOptions(
            name='sit_project',
            options={'verbose_name': 'SIT iktatószám', 'verbose_name_plural': 'SIT iktatószámok'},
        ),
        migrations.AlterModelOptions(
            name='sit_with_date',
            options={'verbose_name': 'Rögzített SIT projekt', 'verbose_name_plural': 'Rögzített SIT projektek'},
        ),
        migrations.AlterModelOptions(
            name='subproject',
            options={'verbose_name': 'Süllyedésmérés iktatószám', 'verbose_name_plural': 'Süllyedésmérés iktatószámok'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'verbose_name': 'Jármű', 'verbose_name_plural': 'Járművek'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='artifact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.artifact', verbose_name='Műtárgy'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Földrajzi szélesség'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='length',
            field=models.IntegerField(blank=True, null=True, verbose_name='Csőhossz'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Földrajzi hosszúság'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='measurement_side',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Mérési oldal'),
        ),
        migrations.AlterField(
            model_name='sit_with_date',
            name='bridge',
            field=models.CharField(max_length=100, verbose_name='Híd jele'),
        ),
        migrations.AlterField(
            model_name='sit_with_date',
            name='building',
            field=models.CharField(max_length=100, verbose_name='Épület/Támasz'),
        ),
        migrations.AlterField(
            model_name='sit_with_date',
            name='no_of_piles',
            field=models.IntegerField(verbose_name='Cölöpök száma'),
        ),
        migrations.AlterField(
            model_name='sit_with_date',
            name='project_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.sit_project', verbose_name='Iktatószám'),
        ),
    ]
