# Generated by Django 4.1.3 on 2022-12-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_date_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date',
            name='projects',
        ),
        migrations.AddField(
            model_name='date',
            name='projects',
            field=models.ManyToManyField(null=True, to='schedule.project'),
        ),
    ]
