# Generated by Django 4.1.3 on 2022-12-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_remove_date_projects_date_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='employees',
            field=models.ManyToManyField(null=True, to='schedule.employee'),
        ),
        migrations.AddField(
            model_name='project',
            name='vehicles',
            field=models.ManyToManyField(null=True, to='schedule.vehicle'),
        ),
    ]
