# Generated by Django 4.1.3 on 2022-12-05 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_project_employees_project_vehicles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='project',
            name='employees',
        ),
        migrations.RemoveField(
            model_name='project',
            name='vehicles',
        ),
        migrations.CreateModel(
            name='DateBoundWithProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='schedule.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='schedule.project')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='schedule.vehicle')),
            ],
        ),
    ]
