# Generated by Django 4.1.3 on 2022-12-05 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_remove_date_projects_remove_project_employees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dateboundwithproject',
            name='date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.date'),
        ),
    ]
