# Generated by Django 4.1.3 on 2022-12-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0013_dateboundwithproject_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dateboundwithproject',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='dateboundwithproject',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='dateboundwithproject',
            name='employee',
            field=models.ManyToManyField(to='schedule.employee'),
        ),
        migrations.AddField(
            model_name='dateboundwithproject',
            name='vehicle',
            field=models.ManyToManyField(to='schedule.vehicle'),
        ),
    ]
