# Generated by Django 4.1.3 on 2022-12-10 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0016_alter_dateboundwithproject_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubProjectName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subproject', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubProjectItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_project_item', models.CharField(max_length=50)),
                ('sub_project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.subprojectname')),
            ],
        ),
    ]
