# Generated by Django 4.1.3 on 2022-12-10 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0017_subprojectname_subprojectitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(max_length=50, verbose_name='Szelvény')),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.artifact')),
            ],
        ),
        migrations.CreateModel(
            name='Subproject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subproject', models.CharField(max_length=50, verbose_name='Projekt')),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_name',
            field=models.CharField(max_length=50, verbose_name='Munkavállaló neve'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nickname',
            field=models.CharField(max_length=30, verbose_name='Munkavállaló beceneve'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='license_plate',
            field=models.CharField(max_length=20, verbose_name='Rendszám'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_name',
            field=models.CharField(max_length=30, verbose_name='Autó neve'),
        ),
        migrations.DeleteModel(
            name='SubProjectItem',
        ),
        migrations.DeleteModel(
            name='SubProjectName',
        ),
        migrations.AddField(
            model_name='artifact',
            name='subproject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.subproject'),
        ),
    ]
