# Generated by Django 4.1.3 on 2022-12-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0018_artifact_profile_subproject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='artifact',
            field=models.CharField(default=1, max_length=50, verbose_name='Műtárgy'),
            preserve_default=False,
        ),
    ]
