# Generated by Django 4.1.3 on 2022-12-10 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0020_subproject_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='dateboundwithproject',
            name='subproject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.subproject'),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='subproject',
            field=models.CharField(max_length=50),
        ),
    ]
