# Generated by Django 4.1.3 on 2022-12-11 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0022_dateboundwithproject_artifact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='artifact',
            field=models.CharField(max_length=50, null=True, verbose_name='Műtárgy'),
        ),
        migrations.RemoveField(
            model_name='dateboundwithproject',
            name='profile',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile',
            field=models.CharField(max_length=50, null=True, verbose_name='Szelvény'),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subproject', to='schedule.project'),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='subproject',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dateboundwithproject',
            name='profile',
            field=models.ManyToManyField(to='schedule.profile'),
        ),
    ]
