# Generated by Django 4.1.3 on 2022-12-11 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0023_alter_artifact_artifact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dateboundwithproject',
            name='profile',
        ),
        migrations.AddField(
            model_name='dateboundwithproject',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.profile'),
        ),
    ]
