# Generated by Django 4.1.3 on 2022-12-11 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0024_remove_dateboundwithproject_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateboundwithproject',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.profile'),
        ),
    ]
