# Generated by Django 4.1.3 on 2022-12-12 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0026_alter_profile_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DateBoundWithProject',
            new_name='DateBoundWithProjectAndSubproject',
        ),
    ]
