# Generated by Django 4.1.3 on 2022-12-12 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0027_rename_dateboundwithproject_dateboundwithprojectandsubproject'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DateBoundWithProjectAndSubproject',
            new_name='DateBoundWithProject',
        ),
    ]
