# Generated by Django 4.1.3 on 2022-12-12 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0028_rename_dateboundwithprojectandsubproject_dateboundwithproject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dateboundwithproject',
            name='profile',
        ),
        migrations.AddField(
            model_name='dateboundwithproject',
            name='profile',
            field=models.ManyToManyField(blank=True, null=True, to='schedule.profile'),
        ),
    ]
