# Generated by Django 4.1.3 on 2022-12-14 18:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0029_remove_dateboundwithproject_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateboundwithproject',
            name='employee',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
