# Generated by Django 4.1.3 on 2022-12-14 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0030_alter_dateboundwithproject_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
