# Generated by Django 4.1.3 on 2022-12-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0031_delete_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dateboundwithproject',
            name='artifact',
        ),
        migrations.RemoveField(
            model_name='dateboundwithproject',
            name='subproject',
        ),
        migrations.AddField(
            model_name='dateboundwithproject',
            name='artifact',
            field=models.ManyToManyField(null=True, to='schedule.artifact'),
        ),
        migrations.AddField(
            model_name='dateboundwithproject',
            name='subproject',
            field=models.ManyToManyField(null=True, to='schedule.subproject'),
        ),
    ]
