# Generated by Django 4.1.3 on 2022-12-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0033_remove_dateboundwithproject_artifact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='length',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='measurement_side',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='subproject',
            name='customer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subproject',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
