# Generated by Django 4.1.3 on 2022-12-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0036_profile_latitude_profile_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='state',
            field=models.CharField(choices=[('untouched', 'untouched'), ('draft', 'draft'), ('done', 'done')], default='untouched', max_length=15),
        ),
    ]
