# Generated by Django 4.1.3 on 2022-12-27 23:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0037_date_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='employees_on_leave',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
