# Generated by Django 4.1.3 on 2023-01-04 21:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0038_date_employees_on_leave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='employees_on_leave',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
