# Generated by Django 4.1.3 on 2023-01-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0039_alter_date_employees_on_leave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateboundwithproject',
            name='profile',
            field=models.ManyToManyField(blank=True, to='schedule.profile'),
        ),
    ]
