# Generated by Django 4.1.3 on 2023-01-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugreport', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='temp',
        ),
        migrations.AddField(
            model_name='bug',
            name='description',
            field=models.TextField(default='d', help_text='A description of the bug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bug',
            name='page',
            field=models.CharField(default='s', help_text='On which page did the bug occur?', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bug',
            name='reporter_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bug',
            name='reporter_project',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bug',
            name='severity',
            field=models.CharField(choices=[('Slight', 'Slight'), ('Mild', 'Mild'), ('Medium', 'Medium'), ('Important', 'Important'), ('Severe', 'Severe')], default='Mild', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bug',
            name='state',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Work in progress', 'Work in progress'), ('Done', 'Done'), ('Closed', 'Closed')], default='Done', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bug',
            name='title',
            field=models.CharField(default='1', max_length=30),
            preserve_default=False,
        ),
    ]
